### ISSUE TITLE
The export name "__esModule" is reserved and cannot be used 

### ISSUE THREAD

**Issue by bjornstar** [addaleax/gen-esm-wrapper#6]
We're having an issue when using esbuild v0.12.7 and importing libraries that use `gen-esm-wrapper`:

- https://github.com/Chevrotain/chevrotain/issues/1537
- https://github.com/jawj/zapatos/issues/92

My initial proposal for `chevrotain` was to use --exclude=__esModule but I think that `__esModule` should probably be excluded by default in `gen-esm-wrapper`.

I think it would be safe to use `Object.keys` instead of `Object.getOwnPropertyNames` so we can exclude non-enumerable properties.

**Comment by addaleax** [comment]
>  but I think that `__esModule` should probably be excluded by default in `gen-esm-wrapper`.

Yeah, that’s fair. Do you want to send a PR? I think just adding a `keys.delete('__esModule')` is fine.

> I think it would be safe to use `Object.keys` instead of `Object.getOwnPropertyNames` so we can exclude non-enumerable properties.

I would lean towards ‘no’ on this – the goal here is for the ESM exports to really match the CJS ones.

**Comment by bjornstar** [comment]
> > but I think that `__esModule` should probably be excluded by default in `gen-esm-wrapper`.
> 
> Yeah, that’s fair. Do you want to send a PR? I think just adding a `keys.delete('__esModule')` is fine.

> > I think it would be safe to use `Object.keys` instead of `Object.getOwnPropertyNames` so we can exclude non-enumerable properties.
> 
> I would lean towards ‘no’ on this – the goal here is for the ESM exports to really match the CJS ones.

The non-enumerated keys for functions and non-objects are being deleted. That logic could be dropped by using `Object.keys`. 

I think it's unexpected that properties which are marked as non-enumerable become enumerable. My impression of non-enumerable properties is that they are being intentionally hidden as an indication they are not for public consumption.

It's not a big deal though, I'll prepare a PR to only delete the `__esModule` key.
