### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by bd82** [addaleax/gen-esm-wrapper#9]
Hello @addaleax 

I'm using `gen-esm-wrapper` to bundle a library I develop so firstly **thanks** for your work 👍 

A recent [issue](https://github.com/Chevrotain/chevrotain/issues/1643) raised some questions regarding how `gen-esm-wrapper` works specifically in regards to default import/exports.

For the example code:
```javascript
'use strict';
// This is a CommonJS module.

exports.method = () => {
  return 'hello';
};
```

 The wrapped esm version would be:
```javascript
import mod from "../index.js";

export default mod;
export const method = mod.method;

```

The questions are:

1. How does the default import `import mod from "../index.js";` work considering the input has **no** default export.
2. Why does the output adds a **default** export even though the input did not have one?
   - Does not this mean a user of a library may have slightly different APIs exposed if they are using the the ESM or the CJS version?

I am probably missing some basic piece of information here, any help would be appreciated 😄 

Thanks.
Shahar.

**Comment by addaleax** [comment]
@bd82 The assumption here is that, when no default export is present, the consumer of the library would expect `import mod from 'mod'` to work like `const mod = require('mod')`, that’s all.

**Comment by bd82** [comment]
Thanks for the quick reply @addaleax 

I found the missing bit in my understanding.

> This shorthand is equivalent to import {default as _} from "lodash";. All CommonJS and AMD modules are presented to ES6 as having a default export, which is the same thing that you would get if you asked require() for that module—that is, the exports object.

- https://hacks.mozilla.org/2015/08/es6-in-depth-modules/

So I guess I should make my library in CommonJS format also have a default export and have it be declared
in the d.ts file so the behavior and consumption in both ESM and CommonJS would be the same.

Thanks 👍
